# Generated by Django 3.1.1 on 2020-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('name', models.CharField(max_length=300)),
                ('product_category', models.CharField(max_length=300)),
                ('product_type', models.CharField(max_length=300)),
                ('attribute', models.TextField(max_length=1000, verbose_name='attribute')),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
            ],
        ),
    ]
