# Generated by Django 3.1.1 on 2020-09-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_auto_20200918_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
    ]
