# Generated by Django 3.1.1 on 2020-09-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0009_customer_order_orderitem_shippingadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
