# Generated by Django 3.1.2 on 2020-10-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0011_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'shirt'), ('jeans', 'jeans'), ('pant', 'pant'), ('shoe', 'shoe'), ('t-shirt', 't-shirt'), ('sunglass', 'sunglass')], max_length=300),
        ),
    ]
