# Generated by Django 3.1.2 on 2020-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0014_auto_20201002_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipped',
            new_name='approve',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Acessories', 'Acessories'), ('Apparel', 'Apparel')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'shirt'), ('t-shirt', 't-shirt'), ('sunglass', 'sunglass'), ('shoe', 'shoe'), ('jeans', 'jeans'), ('pant', 'pant')], max_length=300),
        ),
    ]
