# Generated by Django 3.1.2 on 2020-10-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0015_auto_20201002_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Acessories', 'Acessories')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('t-shirt', 't-shirt'), ('pant', 'pant'), ('jeans', 'jeans'), ('shoe', 'shoe'), ('sunglass', 'sunglass'), ('shirt', 'shirt')], max_length=300),
        ),
    ]
