# Generated by Django 3.1.2 on 2020-10-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0016_auto_20201003_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Acessories', 'Acessories'), ('Apparel', 'Apparel')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'shirt'), ('t-shirt', 't-shirt'), ('jeans', 'jeans'), ('shoe', 'shoe'), ('sunglass', 'sunglass'), ('pant', 'pant')], max_length=300),
        ),
    ]
