# Generated by Django 3.1.2 on 2020-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0017_auto_20201003_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('out for delivery', 'out for delivery'), ('shipped', 'shipped')], default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('pant', 'pant'), ('shoe', 'shoe'), ('shirt', 'shirt'), ('sunglass', 'sunglass'), ('jeans', 'jeans'), ('t-shirt', 't-shirt')], max_length=300),
        ),
    ]
