# Generated by Django 3.1.2 on 2020-10-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0018_auto_20201005_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Acessories', 'Acessories')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sunglass', 'sunglass'), ('shirt', 'shirt'), ('shoe', 'shoe'), ('t-shirt', 't-shirt'), ('jeans', 'jeans'), ('pant', 'pant')], max_length=300),
        ),
    ]
