# Generated by Django 3.1.2 on 2020-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0019_auto_20201005_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Acessories', 'Acessories'), ('Apparel', 'Apparel')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shoe', 'shoe'), ('shirt', 'shirt'), ('t-shirt', 't-shirt'), ('sunglass', 'sunglass'), ('pant', 'pant'), ('jeans', 'jeans')], max_length=300),
        ),
    ]
