# Generated by Django 3.1.2 on 2020-10-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0020_auto_20201005_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Acessories', 'Acessories')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'shirt'), ('jeans', 'jeans'), ('t-shirt', 't-shirt'), ('shoe', 'shoe'), ('pant', 'pant'), ('sunglass', 'sunglass')], max_length=300),
        ),
    ]
