# Generated by Django 3.1.2 on 2020-10-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0021_auto_20201005_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.CharField(default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Acessories', 'Acessories'), ('Apparel', 'Apparel')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('pant', 'pant'), ('shoe', 'shoe'), ('t-shirt', 't-shirt'), ('jeans', 'jeans'), ('sunglass', 'sunglass'), ('shirt', 'shirt')], max_length=300),
        ),
    ]
