# Generated by Django 3.1.2 on 2020-10-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0023_auto_20201006_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.CharField(default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Acessories', 'Acessories'), ('Apparel', 'Apparel')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sunglass', 'sunglass'), ('jeans', 'jeans'), ('shoe', 'shoe'), ('t-shirt', 't-shirt'), ('shirt', 'shirt'), ('pant', 'pant')], max_length=300),
        ),
    ]
