# Generated by Django 3.1.2 on 2020-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0024_auto_20201006_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.CharField(choices=[('pending', 'pending'), ('out for delivery', 'out for delivery'), ('shipped', 'shipped'), ('completed', 'completed')], default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'shirt'), ('jeans', 'jeans'), ('shoe', 'shoe'), ('pant', 'pant'), ('sunglass', 'sunglass'), ('t-shirt', 't-shirt')], max_length=300),
        ),
    ]
