# Generated by Django 3.1.2 on 2020-10-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0025_auto_20201008_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.CharField(choices=[('pending', 'pending'), ('out for delivery', 'out for delivery'), ('completed', 'completed'), ('shipped', 'shipped')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shoe', 'shoe'), ('shirt', 'shirt'), ('sunglass', 'sunglass'), ('t-shirt', 't-shirt'), ('pant', 'pant'), ('jeans', 'jeans')], max_length=300),
        ),
    ]
