# Generated by Django 3.1.2 on 2020-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0026_auto_20201008_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.CharField(default='pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('t-shirt', 't-shirt'), ('shirt', 'shirt'), ('sunglass', 'sunglass'), ('pant', 'pant'), ('shoe', 'shoe'), ('jeans', 'jeans')], max_length=300),
        ),
    ]
