# Generated by Django 3.1.2 on 2020-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0027_auto_20201008_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Acessories', 'Acessories')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sunglass', 'sunglass'), ('t-shirt', 't-shirt'), ('shoe', 'shoe'), ('pant', 'pant'), ('shirt', 'shirt'), ('jeans', 'jeans')], max_length=300),
        ),
    ]
