# Generated by Django 3.1.2 on 2020-10-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0028_auto_20201008_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Acessories', 'Acessories'), ('Apparel', 'Apparel')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shoe', 'shoe'), ('t-shirt', 't-shirt'), ('pant', 'pant'), ('sunglass', 'sunglass'), ('jeans', 'jeans'), ('shirt', 'shirt')], max_length=300),
        ),
    ]
