# Generated by Django 3.1.2 on 2020-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0029_auto_20201009_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='payment_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Acessories', 'Acessories')], max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('jeans', 'jeans'), ('shirt', 'shirt'), ('pant', 'pant'), ('sunglass', 'sunglass'), ('t-shirt', 't-shirt'), ('shoe', 'shoe')], max_length=300),
        ),
    ]
